#!/usr/bin/env node
// pack-and-ship — build the distributable zip, a plain-text-safe copy, and a
// per-platform listing sheet, from one skill directory.
// Usage: node scripts/pack.mjs [targetDir=.]
import fs from 'node:fs';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { sanitize } from './sanitize.mjs';

const dir = path.resolve(process.argv[2] || '.');
const P = p => path.join(dir, p);
const read = p => fs.readFileSync(P(p), 'utf8');
const exists = p => fs.existsSync(P(p));

// ── locate SKILL.md (root or one deep) ──
let skillPath = exists('SKILL.md') ? 'SKILL.md' : null;
if (!skillPath) {
  const d = fs.readdirSync(dir).find(x => { try { return fs.statSync(P(x)).isDirectory() && exists(path.join(x, 'SKILL.md')); } catch { return false; } });
  if (d) skillPath = path.join(d, 'SKILL.md');
}
if (!skillPath) { console.error('No SKILL.md found in', dir); process.exit(2); }
const skill = read(skillPath);
const fm = (skill.match(/^---\n([\s\S]*?)\n---/) || [, ''])[1];
const fmName = (fm.match(/^name:\s*(.+)$/m) || [])[1]?.trim();
const fmDesc = (fm.match(/^description:\s*(.+)$/m) || [])[1]?.trim() || '';
const bodyStartLine = skill.startsWith('---') ? skill.slice(0, skill.indexOf('---', 3) + 3).split('\n').length + 1 : 1;

// ── config (optional) + git remote inference ──
const cfg = exists('ship.config.json') ? JSON.parse(read('ship.config.json')) : {};
let owner = cfg.owner, repo = cfg.repo;
if (!owner || !repo) {
  try {
    const url = execFileSync('git', ['-C', dir, 'remote', 'get-url', 'origin'], { encoding: 'utf8' }).trim();
    // last two path segments work for github.com AND proxied/self-hosted remotes
    const m = url.match(/[:/]([^/]+)\/([^/]+?)(?:\.git)?\/?$/);
    if (m) { owner ||= m[1]; repo ||= m[2]; }
  } catch {}
}
const name = fmName || repo || 'skill';
const install = cfg.install || (owner && repo ? `npx skills add ${owner}/${repo}` : 'npx skills add <owner>/<repo>');
const homepage = cfg.homepage || (owner && repo ? `https://github.com/${owner}/${repo}` : '');
const summary = cfg.summary || fmDesc.split(/(?<=\.)\s/)[0] || fmDesc;
const tags = cfg.tags || [];
const category = cfg.category || '(pick the closest real category — not the default)';
const price = cfg.price || { amount: 0, currency: 'USD', checkoutUrl: '' };
const demo = cfg.demo || {};
const isPaid = Number(price.amount) > 0;

// ── outputs ──
const dist = P('dist');
fs.mkdirSync(dist, { recursive: true });

// 1) zip (exclude dev dirs). Requires `zip`.
const exclude = (cfg.zip?.exclude || ['node_modules', '.git', 'tests', 'dist', '.github']);
const zipName = `${name}.zip`;
try {
  // bare `e` excludes a file; `e/*` excludes a directory's contents — cover both
  execFileSync('zip', ['-rq', path.join('dist', zipName), '.',
    '-x', ...exclude.flatMap(e => [e, `./${e}`, `${e}/*`, `./${e}/*`]), '-x', 'dist/*', '.git/*'], { cwd: dir });
  console.log('✓ dist/' + zipName);
} catch (e) { console.error('! zip failed (is `zip` installed?):', e.message); }

// 2) plain-text-safe copy (for INPUT_GUARD uploaders)
const plainName = `${name}-plaintext.md`;
fs.writeFileSync(path.join(dist, plainName), sanitize(skill));
console.log('✓ dist/' + plainName);

// 3) listing sheet
const bodyForRegistry = skill.startsWith('---') ? skill.slice(skill.indexOf('---', 3) + 3).replace(/^\n+/, '') : skill;
const priceLine = isPaid ? `${price.currency} ${price.amount}` : 'FREE (leave price blank)';
const L = [];
L.push(`# Listing sheet — ${name}`, '');
L.push(`_Generated by pack-and-ship. Copy the fields per platform. See references/platforms.md for gotchas._`, '');
L.push(`| Field | Value |`, `|---|---|`);
L.push(`| Name | ${name} |`);
L.push(`| Owner / Repo | ${owner || '?'} / ${repo || '?'} |`);
L.push(`| Install | \`${install}\` |`);
L.push(`| Homepage | ${homepage} |`);
L.push(`| Summary | ${summary} |`);
L.push(`| Tags | ${tags.join(', ')} |`);
L.push(`| Category | ${category} |`);
L.push(`| Price | ${priceLine}${isPaid && price.checkoutUrl ? ` → ${price.checkoutUrl}` : ''} |`);
if (demo.video) L.push(`| Demo video | ${demo.video} |`);
if (demo.page) L.push(`| Live demo | ${demo.page} |`);
L.push('');
L.push(`## GitHub`);
L.push(`- Commit the repo; README badges + demo; \`.github/FUNDING.yml\` custom URL${isPaid ? ` → ${price.checkoutUrl || '<checkout>'}` : ' (skip if free)'}.`);
L.push(`- Upload a 1280×640 social preview (Settings → General, manual). Enable Sponsorships.`);
L.push('');
L.push(`## Agensi  — upload \`dist/${zipName}\``);
L.push(`- Fields: Name, Category=${category}, Summary, Tags above. Price: ${priceLine}.`);
L.push(`- Permissions: declare honestly (Terminal/Read/Write/Browser as used; Network/Env only if used).`);
L.push(`- Paid needs Stripe payout — if unavailable, list free here and sell via Polar.`);
L.push('');
L.push(`## explainx.ai  — upload \`dist/${plainName}\``);
L.push(`- The raw SKILL.md trips INPUT_GUARD; use the plaintext copy. Category, owner=${owner}, repo=${repo}, install, summary, tags above. Price: ${priceLine}.`);
L.push('');
L.push(`## SkillRegistry  — paste the SKILL.md BODY`);
L.push(`- Name=${name}, slug=${name}, Homepage=${homepage}, Tags above.`);
L.push(`- Skill content = everything from line ${bodyStartLine} of SKILL.md (frontmatter stripped). See dist/${plainName} or the raw body.`);
L.push('');
if (isPaid) {
  L.push(`## Polar (paid)  — attach \`dist/${zipName}\``);
  L.push(`- Fixed price ${price.currency} ${price.amount}; File Download benefit = the zip; Public; add a 16:9 product image.`);
  L.push(`- Create a checkout link, paste it into FUNDING.yml + README badge.`);
  L.push('');
}
L.push(`## Free registries worth a PR`);
L.push(`- awesome-claude-skills style lists (open a PR with the repo), Skills Directory (reviewed), Show HN / Product Hunt (launch with the demo video).`);
fs.writeFileSync(path.join(dist, 'listing.md'), L.join('\n') + '\n');
console.log('✓ dist/listing.md');

console.log(`\nNext: open dist/listing.md and submit. Uploads: Agensi/Polar → ${zipName}; explainx → ${plainName}; SkillRegistry → SKILL.md body.`);
